Transform: AWS::Serverless-2016-10-31

Resources:
  LayerBase:
    Type: AWS::Serverless::LayerVersion
    Properties:
      ContentUri: layers/base

  ParameterLayerArnBase:
    Type: AWS::SSM::Parameter
    Properties:
      Name: /LuciferousDevIoIndex/Layer/Base
      Type: String
      Value: !Ref LayerBase

  LayerFeedparser:
    Type: AWS::Serverless::LayerVersion
    Properties:
      ContentUri: layers/feedparser

  ParameterLayerArnFeedparser:
    Type: AWS::SSM::Parameter
    Properties:
      Name: /LuciferousDevIoIndex/Layer/Feedparser
      Type: String
      Value: !Ref LayerFeedparser

  LayerBs4:
    Type: AWS::Serverless::LayerVersion
    Properties:
      ContentUri: layers/bs4

  ParameterLayerArnBs4:
    Type: AWS::SSM::Parameter
    Properties:
      Name: /LuciferousDevIoIndex/Layer/Bs4
      Type: String
      Value: !Ref LayerBs4

  LayerJinja:
    Type: AWS::Serverless::LayerVersion
    Properties:
      ContentUri: layers/jinja

  ParameterLayerArnJinja:
    Type: AWS::SSM::Parameter
    Properties:
      Name: /LuciferousDevIoIndex/Layer/Jinja
      Type: String
      Value: !Ref LayerJinja
