Transform: AWS::Serverless-2016-10-31

Resources:
  LayerBase:
    Type: AWS::Serverless::LayerVersion
    Properties:
      ContentUri: layers/base

  ParameterLayerArnBase:
    Type: AWS::SSM::Parameter
    Properties:
      Name: /LuciferousDevIoIndex/Layer/Base
      Type: String
      Value: !Ref LayerBase

  LayerFeedparser:
    Type: AWS::Serverless::LayerVersion
    Properties:
      ContentUri: layers/feedparser

  ParameterLayerArnFeedparser:
    Type: AWS::SSM::Parameter
    Properties:
      Name: /LuciferousDevIoIndex/Layer/Feedparser
      Type: String
      Value: !Ref LayerFeedparser
